language: go

go:
 - 1.1
 - tip

script:
  - go get github.com/couchbaselabs/go.assert
  - go test -v ./...
  - go vet ./...

notifications:
  email:
    - dustin@couchbase.com
    - jens@couchbase.com
